# Generated by Django 6.0 on 2025-12-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_conclusao', models.DateField()),
                ('concluida', models.BooleanField(default=False)),
            ],
        ),
    ]
